### ISSUE TITLE
请问，你们的工程 包不包含 elaphureLink.dll的 源码？

### ISSUE THREAD

**Issue by mcu598** [windowsair/elaphureLink#2]
编译时候缺失 git_info.hpp这个文件无非通过。

**Comment by windowsair** [comment]
构建系统会自动生成`git_info.hpp`

详见https://github.com/windowsair/elaphureLink/commit/e87f7204109428227bc62a866b8158ace396067f

**Comment by windowsair** [comment]
`elaphureLink.dll` 的源码在elaphureAGDI下，详见项目文档
