### ISSUE TITLE
更换设备问题？

### ISSUE THREAD

**Issue by ZhiyuanYuanNJ** [windowsair/elaphureLink#8]
你好，我想尝试将ESP8266更换为其他适配器，请问需要修改哪里？

**Comment by windowsair** [comment]
https://github.com/windowsair/elaphureLink/blob/master/docs/server_providers_document.md

参考文档进行操作

**Comment by ZhiyuanYuanNJ** [comment]
感谢，但是我希望的是直接利用keil通过USB与适配器进行通信调试，这样可以省去TCP/IP协议和elaphureLink.Wpf.exe上位机，不知该如何实现?

**Comment by windowsair** [comment]
走 usb 的直接使用 cmsis-dap 不就可以了么，项目没有包含 usb 的部分

**Comment by ZhiyuanYuanNJ** [comment]
是的，但目前都是直接选择keil的cmsis-dap项，不知能否修改elaphureLink.dll，并加在keil中，这样能够在keil中选择其他设备，并提供比cmsis-dap更丰富的功能

**Comment by windowsair** [comment]
那可以参考项目 AGDI 部分进行修改

**Comment by ZhiyuanYuanNJ** [comment]
十分感谢
