### ISSUE TITLE
Keil下非常好用，感谢，请问 如何在IAR中使用？

### ISSUE THREAD

**Issue by sblpp** [windowsair/elaphureLink#9]

**Comment by windowsair** [comment]
IAR 的资料不好搞，我去问一下。

**Comment by sblpp** [comment]
> IAR 的资料不好搞，我去问一下。

感谢大佬~~~

**Comment by windowsair** [comment]
已经一个月了，IAR 没有回复，估计整不了。

**Comment by pengwon** [comment]
大佬，请问keil驱动的资料是如何获取的？我在keil网站找了很久，他们似乎把arm调试器驱动的资料给匿了，只剩下c51的。

**Comment by windowsair** [comment]
> 大佬，请问keil驱动的资料是如何获取的？我在keil网站找了很久，他们似乎把arm调试器驱动的资料给匿了，只剩下c51的。

直接问 arm support 就好。不过现在制裁了，估计是问不了了。

**Comment by pengwon** [comment]
> > 大佬，请问keil驱动的资料是如何获取的？我在keil网站找了很久，他们似乎把arm调试器驱动的资料给匿了，只剩下c51的。
> 
> 直接问 arm support 就好。不过现在制裁了，估计是问不了了。

嗯，前几天发了邮件，一直没有回复，估计凉凉。大佬除了app note 173还参考其他文档了吗？release note中说的切换到agdi开源实现是指哪个项目？还是大佬自己实现的？

**Comment by pengwon** [comment]
@windowsair 大佬，主页邮件能联系到你吗，发了封邮件。
